"""add default game mode

Revision ID: 114f8e191b20
Revises: 85c76a3d8d5a
Create Date: 2019-09-30 19:21:21.397664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '114f8e191b20'
down_revision = '85c76a3d8d5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('games', 'mode',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('games', 'mode',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    # ### end Alembic commands ###
