"""add game mode

Revision ID: 85c76a3d8d5a
Revises: 3ee9f6e73b88
Create Date: 2019-09-30 19:20:23.932454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85c76a3d8d5a'
down_revision = '3ee9f6e73b88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('mode', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'mode')
    # ### end Alembic commands ###
